# Generated by Django 6.0.3 on 2026-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0002_rename_followup_date_followup_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
    ]
