# Generated by Django 6.0.6 on 2026-07-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('CONTACTED', 'CONTACTED'), ('FOLLOWUP', "'FOLLOWUP"), ('INTRESTED', 'INTRESTED'), ('NOT_INTRESTED', 'NOT_INTRESTED')], default='NEW', max_length=20)),
            ],
        ),
    ]
