# Generated by Django 6.0.3 on 2026-07-02 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('CONTACTED', 'CONTACTED'), ('FOLLOWUP', 'FOLLOWUP'), ('INTERESTED', 'INTERESTED'), ('NOT_INTERESTED', 'NOT_INTERESTED')], default='NEW', max_length=20),
        ),
    ]
