# Generated by Django 6.0.3 on 2026-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='product_service',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('CONTACTED', 'CONTACTED'), ('FOLLOWUP', 'FOLLOWUP'), ('INTERESTED', 'INTERESTED'), ('NOT_INTERESTED', 'NOT_INTERESTED'), ('CLOSED', 'CLOSED')], default='NEW', max_length=20),
        ),
    ]
